# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    encode.algorithm: sha512
    encode.use_base64: true
    encode.iterations: 10

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    Core\:
        resource: '../src/Core/*'
        exclude: '../src/Core/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    Core\Controller\:
        resource: '../src/Core/Controller'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    # Исправление ошибки удаления схемы public при создании миграции
    Core\Doctrine\MigrationEventSubscriber:
        tags:
            - { name: doctrine.event_subscriber, connection: default }

    # Хеширование пароля при сохранении сущности
    Core\Security\HashPasswordListener:
        tags:
            - { name: doctrine.event_subscriber, connection: default }

    Core\Command\NewTextCommand:
        arguments: [ '@doctrine.orm.entity_manager']
        tags:
          - { name: 'console.command' }


